### ISSUE TITLE
Ripping step can be avoided

### ISSUE THREAD

**Issue by randomstuff** [nobodywasishere/auto-libray#1]
You can actually avoid the ripping step (a least on Linux):

```python
libray -i /dev/sr0 -o $RIPLOC_CNT/$gamename.dec.iso
```

**Comment by randomstuff** [comment]
OK, no it does not actually work. Trying to get the fix in `libray` :)

**Comment by randomstuff** [comment]
I submitted a PR to libray to be able to decrypt directly from the disc without creating a temporary ISO file.

**Comment by randomstuff** [comment]
This change is now merged in libray.

**Comment by nobodywasishere** [comment]
I wanted to preserve the encrypted iso with this script, though thanks for the heads up.
